apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rpg-dice-mcp
resources:
  - namespace.yaml
  - harbor-pull-secret.yaml
  - deployment.yaml
  - service.yaml
  - image-updater-rbac.yaml
